[book]
authors = ["Michael Orlando"]
language = "de"
src = "src"
title = "SL-Configurator Documentation"
description = "Comprehensive documentation for the esave SL-Configurator software - A powerful tool for configuring and managing lighting systems with SL-Controllers"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/Lazer-Mic/SL-Configurator-Docs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/Lazer-Mic/SL-Configurator-Docs/edit/main/de/src/{path}"
fold.enable = true
fold.level = 0
git-repository-content-path = "de/src"
numbered-chapters = false
no-section-label = true

[output.html.search]
use-boolean-and = true
prebuild-index = true 
site-url = "/SL-Configurator-Docs/"

# Force rebuild for image path fix
